version: "3.9"
services:
  api:
    build:
      context: api/ArtyApp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
  webapp:
    build:
      context: webapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"