name: SonarCloud Check .NET API 

on:
  push:
    branches:
      - master
    paths:
      - api
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_API }}
        shell: bash
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_NAME_API }}" /o:"${{ secrets.SONAR_ORGANIZATION }}" /d:sonar.login="${{ secrets.SONAR_TOKEN_API }}" /d:sonar.host.url="https://sonarcloud.io"
          dotnet build api/ArtyApp/ArtyApp.sln
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN_API }}"