name: SonarCloud Check

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup SonarCloud
      uses: sonarsource/sonarcloud-github-action@master
      with:
        sonarcloud_organization: ${{ secrets.SONAR_ORGANIZATION }}
        sonarcloud_token: ${{ secrets.SONAR_TOKEN }}
    - name: Analyze with SonarCloud
      run: sonar-scanner begin /k:"your-project-key" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.azurefunctions.analyze.skip=false
    - name: Build solution
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test --configuration Release
    - name: End analysis
      run: sonar-scanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"