name: Deploy to OpenShift

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install OpenShift CLI
      run: |
        VERSION=4.7
        URL=https://mirror.openshift.com/pub/openshift-v4/clients/oc/${VERSION}/linux/oc.tar.gz
        wget $URL
        tar xvfz oc.tar.gz
        chmod +x oc
        mv oc /usr/local/bin/

    - name: Login to OpenShift
      run: oc login --token=${{ secrets.OC_TOKEN }} --server=https://api.sandbox-m3.1530.p1.openshiftapps.com:6443

    - name: Deploy to OpenShift
      run: |
        oc apply -f k8s/

    - name: Check Deployment
      run: oc rollout status deployment/my-deployment
