name: Build and Deploy on Azure

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{ secrets.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Build and package
      shell: pwsh
      run: dotnet build --configuration Release

    - name: Test
      shell: pwsh
      run: dotnet test --configuration Release

  deploy:
    needs: build-and-test
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set environment variables
      run: |
        echo set BotConfiguration__BotToken=${{ secrets.BOT_TOKEN }} >> "$env:ProgramData\chocolatey\bin\setenv.cmd"
        echo set BotConfiguration__HostAddress=${{ secrets.AZURE_HOST }} >> "$env:ProgramData\chocolatey\bin\setenv.cmd"
        echo set CurrencyExchangeConfiguration__CurrencyExchangeKey=${{ secrets.CURRENCY_API_KEY }} >> "$env:ProgramData\chocolatey\bin\setenv.cmd"
      shell: pwsh
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        dotnet build --configuration Release --output ./output
        popd
    - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
