name: Build and Deploy on Somee.com

on:
  push:
    branches: [ "master" ]

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
  build:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
  deploy:
    needs: [prepare, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Replace values in appsettings.json
      run: |
        sed -i "s/\"BotToken\": \"[^\"]*\"/\"BotToken\": \"${{ secrets.BOT_TOKEN }}\"/g" TelegramBotFromArty_Prof/appsettings.json
        sed -i "s/\"CurrencyExchangeKey\": \"[^\"]*\"/\"CurrencyExchangeKey\": \"${{ secrets.CURRENCY_API_KEY }}\"/g" TelegramBotFromArty_Prof/appsettings.json
    - name: Build and publish
      run: |
        dotnet publish -c Release -o out -p:AppsettingsFile=appsettings.json
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: ${{ secrets.FTP_SERVER_DIR }}
        local-dir: ${{ secrets.FTP_LOCAL_DIR }}
