name: Deploy to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.0.x

    - name: Build and Publish
      run: dotnet publish -c Release -o out

    - name: Login to Heroku
      run: heroku login -i

    - name: Deploy to Heroku
      run: heroku container:push web -a telegram-bot-from-artyprof
